---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/kubernetes-helm/tiller

inputs:
  - name: peters-pipelines
  - name: kube-config

run:
  path: peters-pipelines/kubernetes/tasks/setup-tiller/task.sh