---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

inputs:
  - name: pks-scripts
  - name: pks-config
  - name: pks-clusters
outputs:
  - name: pks-clusters-updated

run:
  path: pks-scripts/pks/tasks/resolve-clusters-needs/task.sh