resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: peters-pipelines
  type: git
  source:
    uri: git@github.com:Oskoss/peters-pipelines.git
    private_key: {{github_private_key}}
- name: pcf-ops-manager
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
- name: srt
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver
jobs:
- name: deploy-opsman
  plan:
  - aggregate:
    - get: peters-pipelines
    - get: pivnet-opsman-product
      resource: pcf-ops-manager
      params: {globs: ["*.ova"]}

  - task: deploy
    file: peters-pipelines/pcf/tasks/vsphere-upload-opsman/task.yml
    params:
      GOVC_INSECURE: {{vcenter_insecure}}
      GOVC_CA_CERT: {{vcenter_ca_cert}}
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_DATASTORE: {{vcenter_datastore}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      GOVC_HOST: {{om_vm_host}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OM_VM_FOLDER: {{om_vm_folder}}
      OPS_MGR_SSH_PWD: {{opsman_ssh_password}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_NETMASK: {{om_netmask}}
      OM_IP: {{om_ip}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_NAME: {{om_vm_name}}
      OPSMAN_DISK_TYPE: {{opsman_disk_type}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}

  - task: config-auth
    file: peters-pipelines/pcf/tasks/config-opsman-auth/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}

- name: configure-ops-director
  plan:
  - aggregate:
    - get: peters-pipelines
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-opsman]
      trigger: true

  - task: configure-tile
    file: peters-pipelines/pcf/tasks/vsphere-config-opsman-tile/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}
      VCENTER_DATA_CENTER: {{vcenter_datacenter}}
      VCENTER_DISK_TYPE: {{vm_disk_type}}
      EPHEMERAL_STORAGE_NAMES: {{ephemeral_storage_names}}
      PERSISTENT_STORAGE_NAMES: {{persistent_storage_names}}
      BOSH_VM_FOLDER:  {{bosh_vm_folder}}
      BOSH_TEMPLATE_FOLDER: {{bosh_template_folder}}
      BOSH_DISK_PATH: {{bosh_disk_path}}
      ICMP_CHECKS_ENABLED: {{icmp_checks_enabled}}
      NETWORK_NAME: {{network_name}}
      VCENTER_NETWORK: {{vsphere_network}}
      NW_CIDR: {{nw_cidr}}
      EXCLUDED_RANGE: {{excluded_range}}
      NW_DNS: {{nw_dns}}
      NW_GATEWAY: {{nw_gateway}}
      NW_AZS: {{nw_azs}}
      AZ_1: {{az_1_name}}
      AZ_1_CLUSTER_NAME: {{az_1_cluster_name}}
      AZ_1_RP_NAME: {{az_1_rp_name}}
      NTP_SERVERS: {{ntp_servers}}
      OPS_DIR_HOSTNAME: {{ops_dir_hostname}}
      ENABLE_VM_RESURRECTOR: {{enable_vm_resurrector}}
      MAX_THREADS: {{max_threads}}
      TRUSTED_CERTIFICATES: {{trusted_certificates}}
      NSX_NETWORKING_ENABLED: {{nsx_networking_enabled}}
      NSX_ADDRESS: {{nsx_address}}
      NSX_USERNAME: {{nsx_username}}
      NSX_PASSWORD: {{nsx_password}}
      NSX_CA_CERTIFICATE: {{nsx_ca_certificate}}

- name: apply-changes-opsman-tile
  plan:
  - aggregate:
    - get: peters-pipelines
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [configure-ops-director]
      trigger: true

  - task: apply-changes
    file: peters-pipelines/pcf/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}

- name: upload-SRT-PAS
  plan:
  - aggregate:
    - get: peters-pipelines
    - get: pivnet-product
      resource: srt
      params: {globs: ["srt*.pivotal"]}
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [configure-ops-director]
      trigger: true

  - task: upload-srt-tile
    file: pcf-pipelines/pcf/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: "vsphere"
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      PIVNET_API_TOKEN: {{pivnet_token}}
      NO_PROXY: {{company_proxy_domain}}
      OM_IP: {{om_ip}}

- name: stage-SRT-PAS
  plan:
  - aggregate:
    - get: peters-pipelines
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [upload-SRT-PAS]
      trigger: true
    - get: pivnet-product
      resource: srt
      params: {globs: ["srt*.pivotal"]}
      passed: [upload-SRT-PAS]

  - task: stage
    file: peters-pipelines/pcf/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""