---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.homeoffice.wal-mart.com/library/oskoss/pks     
    insecure_registries: ["harbor.homeoffice.wal-mart.com"]

inputs:
  - name: pks-scripts
  - name: pks-config
  - name: pks-clusters
outputs:
  - name: pks-clusters-updated
params:
  PKS_CLUSTER_JSON_FILE:

run:
  path: pks-scripts/pks/tasks/determine-clusters-needs/task.sh