---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

inputs:
  - name: peters-pipelines
  - name: pks-config
  - name: pks-clusters
params:
  PKS_CLUSTER_JSON_FILE:

run:
  path: peters-pipelines/pks/tasks/determine-clusters-needs/task.sh