---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

params: 
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  IAAS:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  NETWORK_NAME:
  AZ_1_CLUSTER_NAME:
  PKS_API:
  PKS_STORAGE_NAME:
  NSX_NETWORKING_ENABLED:
  NSX_ADDRESS:
  NSX_USERNAME:
  NSX_PASSWORD:
  NSX_CA_CERTIFICATE:
  NSX_NODES_IP_BLOCK_ID:
  NSX_IP_BLOCK_ID:
  NSX_FLOATING_IP_POOL_ID:
  NSX_TO_ROUTER_ID:
  NSX_PI_CERT: 
  NSX_PI_KEY: 
  NW_DNS:
  PKS_VMS:
  NW_AZS:
  CONTAINER_NETWORKING_NW_CIDR:
  CREDUB_ENCRYPTION_KEY_NAME1:
  CREDUB_ENCRYPTION_KEY_SECRET1:
  CREDHUB_PRIMARY_ENCRYPTION_NAME:
  POE_SSL_NAME1:
  POE_SSL_CERT1:
  POE_SSL_KEY1:
  POE_SSL_NAME2:
  POE_SSL_CERT2:
  POE_SSL_KEY2:
  POE_SSL_NAME3:
  POE_SSL_CERT3:
  POE_SSL_KEY3:


inputs:
  - name: peters-pipelines

run:
  path: peters-pipelines/pks/tasks/config-pks-tile/task.sh