---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: peters-pipelines
  - name: pivnet-product

outputs:
  - name: pivnet-product

run:
  path: peters-pipelines/pas/tasks/inject-pasw-tile/task.sh