---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

inputs:
  - name: peters-pipelines
  - name: pks-prometheus
  - name: pks-config

run:
  path: peters-pipelines/kubernetes/tasks/create-prometheus-config-map/task.sh