platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
  - name: peters-pipelines
  - name: configuration

run:
  path: peters-pipelines/pcf/tasks/config-product/task.sh

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PRODUCT_NAME:
  PRODUCT_CONFIG_YAML: