---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

params:
  K8S_NAMESPACE:

inputs:
  - name: peters-pipelines
  - name: pks-prometheus
  - name: kube-config

run:
  path: peters-pipelines/kubernetes/tasks/create-prometheus-cluster-user/task.sh