---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

params:
  HEALTHWATCH_URL:
  HEALTHWATCH_USERNAME:
  HEALTHWATCH_PASSWORD:

inputs:
  - name: peters-pipelines

run:
  path: pcf-pipelines/install-pcf/vsphere/tasks/config-opsdir/task.sh