---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: mysql

params:
  HW_DATA_ACCESS_URL:
  
inputs:
  - name: peters-pipelines

run:
  path: peters-pipelines/foundation-health/tasks/ops-man/task.sh