---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.homeoffice.wal-mart.com/library/oskoss/pks     
    insecure_registries: ["harbor.homeoffice.wal-mart.com"]

params:
  PKS_CLUSTER_PREFIX:
  PKS_CLUSTER_PLAN:
  PKS_CLUSTER_HOSTNAME:

inputs:
  - name: pks-scripts
  - name: pks-config

run:
  path: pks-scripts/pks/tasks/create-cluster/task.sh