---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

params:
  PKS_CLUSTER_PREFIX:
  PKS_CLUSTER_PLAN:
  PKS_CLUSTER_HOSTNAME:

inputs:
  - name: peters-pipelines
  - name: pks-config

run:
  path: peters-pipelines/pks/tasks/create-cluster/task.sh