---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

params:
  CF_API_URL:
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
inputs:
  - name: peters-pipelines
  - name: hw-data-access

run:
  path: peters-pipelines/foundation-health/tasks/push-hw-data-access/task.sh