---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

params:
  CF_API_URL:

inputs:
  - name: peters-pipelines

run:
  path: peters-pipelines/foundation-health/tasks/uaa-login/task.sh