---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

params:
  SYS_ENDPOINT:
  ADMIN_PASSWORD:

inputs:
  - name: peters-pipelines

run:
  path: peters-pipelines/foundation-health/tasks/cli/task.sh