resources:
- name: peters-pipelines
  type: git
  source:
    uri: git@github.com:Oskoss/peters-pipelines.git
    private_key: {{github_private_key}}
- name: hw-data-access
  type: git
  source:
    uri: git@github.com:Oskoss/hw-data-access.git
    private_key: {{github_private_key}}
- name: 5m
  type: time
  source: {interval: 5m}

jobs:
- name: push-hw-data-access
  plan:
  - get: peters-pipelines
  - get: hw-data-access
  - task: push-app
    file: peters-pipelines/foundation-health/tasks/push-hw-data-access/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
      CF_PASSWORD: {{cf_password}}
      HEALTHWATCH_MYSQL_IP: {{healthwatch_mysql_ip}}
      HEALTHWATCH_MYSQL_ADMIN_PASSWORD: {{healthwatch_mysql_admin_password}}
- name: healthwatch-avilablity
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: ping
    file: peters-pipelines/foundation-health/tasks/healthwatch-availability/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: uaa-login
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: login
    file: peters-pipelines/foundation-health/tasks/uaa-login/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: cli
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/cli/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: apps-man
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/apps-man/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: ops-man
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/ops-man/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: log-loss
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/log-loss/task.yml
    params:
      CF_API_URL: {{cf_api_url}}