resources:
- name: peters-pipelines
  type: git
  source:
    uri: git@github.com:Oskoss/peters-pipelines.git
    private_key: {{github_private_key}}
- name: 5m
  type: time
  source: {interval: 5m}

jobs:
- name: healthwatch-avilablity
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: ping
    file: peters-pipelines/foundation-health/tasks/healthwatch-availability/task.yml
    params:
      SYS_ENDPOINT: {{sys_endpoint}}
- name: uaa-login
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: login
    file: peters-pipelines/foundation-health/tasks/uaa-login/task.yml
    params:
      SYS_ENDPOINT: {{sys_endpoint}}
      ADMIN_PASSWORD: {{admin_password}}
- name: cli
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/cli/task.yml
    params:
      SYS_ENDPOINT: {{sys_endpoint}}
      ADMIN_PASSWORD: {{admin_password}}
- name: apps-man
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/apps-man/task.yml
    params:
      SYS_ENDPOINT: {{sys_endpoint}}
      ADMIN_PASSWORD: {{admin_password}}