resources:
- name: peters-pipelines
  type: git
  source:
    uri: git@github.com:Oskoss/peters-pipelines.git
    private_key: {{github_private_key}}
- name: hw-data-access
  type: git
  source:
    uri: git@github.com:Oskoss/hw-data-access.git
    private_key: {{github_private_key}}
- name: 5m
  type: time
  source: {interval: 5m}
jobs:
- name: push-hw-data-access
  plan:
  - get: peters-pipelines
  - get: hw-data-access
  - task: push-app
    file: peters-pipelines/foundation-health/tasks/push-hw-data-access/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
      OPSMAN_URL: {{opsman_url}}
      OPSMAN_USERNAME: {{opsman_username}}
      OPSMAN_PASSWORD: {{opsman_password}}
- name: healthwatch-avilablity
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: ping
    file: peters-pipelines/foundation-health/tasks/healthwatch-availability/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: uaa-login
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: login
    file: peters-pipelines/foundation-health/tasks/uaa-login/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: cli-push
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli-push
    file: peters-pipelines/foundation-health/tasks/cli-push/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: cli-start
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
    passed: [cli-push]
  - task: cli-start
    file: peters-pipelines/foundation-health/tasks/cli-start/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: cli-logs
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
    passed: [cli-start]
  - task: cli-logs
    file: peters-pipelines/foundation-health/tasks/cli-logs/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: cli-stop
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
    passed: [cli-logs]
  - task: cli-stop
    file: peters-pipelines/foundation-health/tasks/cli-stop/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: cli-delete
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
    passed: [cli-stop]
  - task: cli-push
    file: peters-pipelines/foundation-health/tasks/cli-delete/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: apps-man
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/apps-man/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: ops-man
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/ops-man/task.yml
    params:
      CF_API_URL: {{cf_api_url}}
- name: log-loss
  plan:
  - get: 5m
    trigger: true
  - get: peters-pipelines
  - task: cli
    file: peters-pipelines/foundation-health/tasks/log-loss/task.yml
    params:
      CF_API_URL: {{cf_api_url}}