---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

params:
  HW_DATA_ACCESS_URL:

inputs:
  - name: peters-pipelines

run:
  path: peters-pipelines/foundation-health/tasks/log-loss/task.sh