---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/kubernetes-helm/tiller
    tag: canary

params:
  RELEASE_NAME:
  CHART_NAME:
  CHART_VALUES:

inputs:
  - name: peters-pipelines
  - name: kube-config
  - name: helm-values

run:
  path: /bin/sh
  args:
    - peters-pipelines/kubernetes/tasks/install-helm-chart/task.sh