---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

params:
  PKS_API_URL:
  PKS_API_USERNAME:
  PKS_API_PASSWORD:

inputs:
  - name: pks-scripts

outputs:
  - name: pks-config
  
run:
  path: pks-scripts/pks/tasks/authenticate-pks/task.sh