---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: oskoss/pks

params:
  PKS_CLUSTER_NAME:

inputs:
  - name: peters-pipelines
  - name: pks-config

run:
  path: peters-pipelines/pks/tasks/get-cluster/task.sh