---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.homeoffice.wal-mart.com/library/oskoss/pks

params:
  PKS_CLUSTER_NAME:

inputs:
  - name: pks-scripts
  - name: pks-config

run:
  path: pks-scripts/pks/tasks/get-cluster/task.sh